config/routes.rb
Rails.application.routes.draw do
  resolve("ActiveStorage::Variant") {|variant, options| main_app.route_for(:rails_variant, variant, options)}


  resources :ticket_prices
  resources :menu_items
  resources :branches
  resources :orders
  resources :cities do
    get :update_data_base, :on => :collection
    get :update_data_base1, :on => :collection
    get :all_cities, :on => :collection
    get :locations_based_on_city, :on => :collection
    get :menu_based_on_location, :on => :collection
    get :tickets_based_on_menu, :on => :collection
  end

  resources :cart_items do
    get :homePage, :on => :collection
    get :division_based_branches, :on => :collection
    get :branch_menu, :on => :collection
    get :display_cart, :on => :collection
    get :change_cart_items, :on => :collection
    get :contactUs, :on => :collection
    get :aboutUs, :on => :collection
    post :place_order, :on => :collection
    post :pay_zippy_response, :on => :collection
    get :orderRecipt, :on => :collection
    get :cityBranchMenu, :on => :collection
    get :test_crm, :on => :collection
  end

  get "cc_avenue/dataFrom"

  get "cc_avenue/ccavRequestHandler"

  post "cc_avenue/ccavResponseHandler"

  root 'cart_items#homePage'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/branch.rb
class Branch < ApplicationRecord
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
  before_action :set_branch, only: [:show, :edit, :update, :destroy]

  # GET /branches
  # GET /branches.json
  def index
    @branches = Branch.all
  end

  # GET /branches/1
  # GET /branches/1.json
  def show
  end

  # GET /branches/new
  def new
    @branch = Branch.new
  end

  # GET /branches/1/edit
  def edit
  end

  # POST /branches
  # POST /branches.json
  def create
    @branch = Branch.new(branch_params)

    respond_to do |format|
      if @branch.save
        format.html { redirect_to "/branches", notice: 'Branch was successfully created.' }
        format.json { render :show, status: :created, location: @branch }
      else
        format.html { render :new }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /branches/1
  # PATCH/PUT /branches/1.json
  def update
    respond_to do |format|
      if @branch.update(branch_params)
        format.html { redirect_to "/branches", notice: 'Branch was successfully updated.' }
        format.json { render :show, status: :ok, location: @branch }
      else
        format.html { render :edit }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /branches/1
  # DELETE /branches/1.json
  def destroy
    @branch.destroy
    respond_to do |format|
      format.html { redirect_to branches_url, notice: 'Branch was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_branch
      @branch = Branch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def branch_params
      params.require(:branch).permit(:city_id, :name, :branch_code, :exit_id, :is_private, :is_active)
    end
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/views/branches/_form.html.erb
<%= form_with(model: branch, local: true) do |form| %>
  <% if branch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(branch.errors.count, "error") %> prohibited this branch from being saved:</h2>

      <ul>
        <% branch.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-sm-6">
      <div class="form-group">
        <%= form.label :name , :class => 'control-label', :style => "text-transform: capitalize;" %>  <br/>
        <%= form.text_field :name, :class => 'form-control', :placeholder => 'Name', :required => true %>
      </div>
      <div class="form-group">
        <%= form.label :branch_code , :class => 'control-label', :style => "text-transform: capitalize;" %>  <br/>
        <%= form.text_field :branch_code, :class => 'form-control', :placeholder => 'Code', :required => true %>
      </div>
      <div class="form-group">
        <%= form.label :exit_id , :class => 'control-label', :style => "text-transform: capitalize;" %>  <br/>
        <%= form.number_field :exit_id , :class => 'form-control', :required => true %>
      </div>
      <div class="form-group">
        <%= form.label :is_private , :class => 'control-label', :style => "text-transform: capitalize;" %>  <br/>
        <%= form.check_box :is_private %>
      </div>
      <div class="form-group">
        <%= form.label :is_active , :class => 'control-label', :style => "text-transform: capitalize;" %>  <br/>
        <%= form.check_box :is_active %>
      </div>
      <div class="form-group">
        <%= form.label :city_id , :class => 'control-label', :style => "text-transform: capitalize;" %>  <br/>
        <%= form.select(:city_id, options_for_select(City.all.collect {|u| [u.name, u.id]}, @branch.city_id), {:prompt => 'Select City '}, :class => 'form-control') %>
      </div>
      <div class="actions">
        <%= form.submit(:class => 'btn btn-primary', :style => 'background-color:#0575AF') %>
      </div>
    </div>
  </div>
<% end %>

app/views/branches/edit.html.erb
<div class="card">
  <div class="card-body">
    <div class="row">
      <div class="col-sm-6"><%= get_index_text('Edit Branch') %></div>
      <div class="col-sm-6 text-right"><%= link_to 'Back', branches_path, :class => 'btn btn-primary', :style => 'color:white;background-color:#125687 !important' %></div>
    </div>
    <%= render 'form', branch: @branch %>
  </div>
</div>

app/views/branches/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-sm-6"><%= get_index_text('Branches') %></div>
  <div class="col-sm-6 text-right"><%= link_to 'New Branch', new_branch_path, :class => 'btn btn-primary', :style => 'color:white;background-color:#125687 !important' %></div>
</div>
<div class="table-responsive">
  <table id="zero_config" class="table table-striped table-bordered">
    <thead>
    <tr class="tr_style">
      <th>Id</th>
      <th>City</th>
      <th>Name</th>
      <th>Branch code</th>
      <th>Exit</th>
      <th>Is private</th>
      <th>Is active</th>
      <th colspan="2"></th>
    </tr>
    </thead>
    <tbody>
    <% @branches.each do |branch| %>
      <tr>
        <td><%= branch.id %></td>
        <td><%= City.find_by_id(branch.city_id).try(:name) %></td>
        <td><%= branch.name %></td>
        <td><%= branch.branch_code %></td>
        <td><%= branch.exit_id %></td>
        <td><%= branch.is_private %></td>
        <td><%= branch.is_active %></td>
        <td><%= link_to 'Edit', edit_branch_path(branch) %></td>
        <td><%= link_to 'Destroy', branch, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
<br>

app/views/branches/new.html.erb
<div class="card">
  <div class="card-body">
    <div class="row">
      <div class="col-sm-6"><%= get_index_text('New Branch') %></div>
      <div class="col-sm-6 text-right"><%= link_to 'Back', branches_path, :class => 'btn btn-primary', :style => 'color:white;background-color:#125687 !important' %></div>
    </div>
    <%= render 'form', branch: @branch %>
  </div>
</div>