config/routes.rb
Rails.application.routes.draw do
  resolve("ActiveStorage::Variant") {|variant, options| main_app.route_for(:rails_variant, variant, options)}


  resources :ticket_prices
  resources :menu_items
  resources :branches
  resources :orders
  resources :cities do
    get :update_data_base, :on => :collection
    get :update_data_base1, :on => :collection
    get :all_cities, :on => :collection
    get :locations_based_on_city, :on => :collection
    get :menu_based_on_location, :on => :collection
    get :tickets_based_on_menu, :on => :collection
  end

  resources :cart_items do
    get :homePage, :on => :collection
    get :division_based_branches, :on => :collection
    get :branch_menu, :on => :collection
    get :display_cart, :on => :collection
    get :change_cart_items, :on => :collection
    get :contactUs, :on => :collection
    get :aboutUs, :on => :collection
    post :place_order, :on => :collection
    post :pay_zippy_response, :on => :collection
    get :orderRecipt, :on => :collection
    get :cityBranchMenu, :on => :collection
    get :test_crm, :on => :collection
  end

  get "cc_avenue/dataFrom"

  get "cc_avenue/ccavRequestHandler"

  post "cc_avenue/ccavResponseHandler"

  root 'cart_items#homePage'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ticket_price.rb
class TicketPrice < ApplicationRecord
end

app/controllers/ticket_prices_controller.rb
class TicketPricesController < ApplicationController
  before_action :set_ticket_price, only: [:show, :edit, :update, :destroy]

  # GET /ticket_prices
  # GET /ticket_prices.json
  def index
    @ticket_prices = TicketPrice.all
  end

  # GET /ticket_prices/1
  # GET /ticket_prices/1.json
  def show
  end

  # GET /ticket_prices/new
  def new
    @ticket_price = TicketPrice.new
  end

  # GET /ticket_prices/1/edit
  def edit
  end

  # POST /ticket_prices
  # POST /ticket_prices.json
  def create
    @ticket_price = TicketPrice.new(ticket_price_params)

    respond_to do |format|
      if @ticket_price.save
        format.html { redirect_to "/ticket_prices", notice: 'Ticket price was successfully created.' }
        format.json { render :show, status: :created, location: @ticket_price }
      else
        format.html { render :new }
        format.json { render json: @ticket_price.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ticket_prices/1
  # PATCH/PUT /ticket_prices/1.json
  def update
    respond_to do |format|
      if @ticket_price.update(ticket_price_params)
        format.html { redirect_to "/ticket_prices", notice: 'Ticket price was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket_price }
      else
        format.html { render :edit }
        format.json { render json: @ticket_price.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ticket_prices/1
  # DELETE /ticket_prices/1.json
  def destroy
    @ticket_price.destroy
    respond_to do |format|
      format.html { redirect_to ticket_prices_url, notice: 'Ticket price was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket_price
      @ticket_price = TicketPrice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_price_params
      params.require(:ticket_price).permit(:name, :price, :city_id, :branch_id, :menu_id, :menu_name, :is_active, :exit_id)
    end
end

app/helpers/ticket_prices_helper.rb
module TicketPricesHelper
end

app/views/ticket_prices/_form.html.erb
<%= form_with(model: ticket_price, local: true) do |form| %>
  <% if ticket_price.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket_price.errors.count, "error") %> prohibited this ticket_price from being saved:</h2>

      <ul>
        <% ticket_price.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-sm-6">
      <div class="form-group">
        <%= form.label :name , :class => 'control-label', :style => "text-transform: capitalize;" %>  <br/>
        <%= form.text_field :name, :class => 'form-control', :placeholder => 'Name', :required => true %>
      </div>

      <div class="field">
        <%= form.label :price , :class => 'control-label', :style => "text-transform: capitalize;" %>  <br/>
        <%= form.text_field :price, :class => 'form-control', :placeholder => 'Name', :required => true %>
      </div>

      <div class="field">
        <%= form.label :city_id , :class => 'control-label', :style => "text-transform: capitalize;" %>  <br/>
        <%= form.select(:city_id, options_for_select(City.all.collect {|u| [u.name, u.id]}, @ticket_price.city_id), {:prompt => 'Select City '}, :class => 'form-control') %>
      </div>

      <div class="field">
        <%= form.label :branch_id , :class => 'control-label', :style => "text-transform: capitalize;" %>  <br/>
        <%= form.select(:branch_id, options_for_select(Branch.all.collect {|u| [u.name, u.id]}, @ticket_price.branch_id), {:prompt => 'Select Branch '}, :class => 'form-control') %>
      </div>

      <div class="field">
        <%= form.label :menu_id , :class => 'control-label', :style => "text-transform: capitalize;" %>  <br/>
        <%= form.select(:menu_id, options_for_select(MenuItem.all.collect {|u| [u.name, u.id]}, @ticket_price.menu_id), {:prompt => 'Select Menu '}, :class => 'form-control') %>
      </div>

    <!--  <div class="field">
        <%#= form.label :menu_name , :class => 'control-label', :style => "text-transform: capitalize;" %>  <br/>
        <%#= form.text_field :menu_name, :class => 'form-control', :placeholder => 'Name', :required => true %>
      </div>-->

      <div class="field">
        <%= form.label :is_active , :class => 'control-label', :style => "text-transform: capitalize;" %>  <br/>
        <%= form.check_box :is_active %>
      </div>

      <div class="field">
        <%= form.label :exit_id , :class => 'control-label', :style => "text-transform: capitalize;" %>  <br/>
        <%= form.number_field :exit_id , :class => 'form-control', :placeholder => 'Name', :required => true %>
      </div>

      <div class="actions">
        <%= form.submit(:class => 'btn btn-primary', :style => 'background-color:#0575AF') %>
      </div>
    </div>
  </div>
<% end %>

app/views/ticket_prices/edit.html.erb
<div class="card">
  <div class="card-body">
    <div class="row">
      <div class="col-sm-6"><%= get_index_text('Edit Ticket Price') %></div>
      <div class="col-sm-6 text-right"><%= link_to 'Back', ticket_prices_path, :class => 'btn btn-primary', :style => 'color:white;background-color:#125687 !important' %></div>
    </div>
    <%= render 'form', ticket_price: @ticket_price %>
  </div>
</div>

app/views/ticket_prices/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-sm-6"><%= get_index_text('Ticket Prices') %></div>
  <div class="col-sm-6 text-right"><%= link_to 'New Ticket Price', new_ticket_price_path, :class => 'btn btn-primary', :style => 'color:white;background-color:#125687 !important' %></div>
</div>
<div class="table-responsive">
  <table id="zero_config" class="table table-striped table-bordered">
    <thead>
    <tr class="tr_style">
      <th>Name</th>
      <th>Price</th>
      <th>City</th>
      <th>Branch</th>
      <th>Menu name</th>
      <th>Is active</th>
      <th>Exit</th>
      <th colspan="2"></th>
    </tr>
    </thead>
    <tbody>
    <% @ticket_prices.each do |ticket_price| %>
      <tr>
        <td><%= ticket_price.name %></td>
        <td><%= ticket_price.price %></td>
        <td><%= City.find_by_id(ticket_price.city_id).try(:name) %></td>
        <td><%= Branch.find_by_id(ticket_price.branch_id).try(:name) %></td>
        <td><%= MenuItem.find_by_id(ticket_price.menu_id).try(:name) %></td>
        <td><%= ticket_price.is_active %></td>
        <td><%= ticket_price.exit_id %></td>
        <td><%= link_to 'Edit', edit_ticket_price_path(ticket_price) %></td>
        <td><%= link_to 'Destroy', ticket_price, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

<br>

app/views/ticket_prices/new.html.erb
<div class="card">
  <div class="card-body">
    <div class="row">
      <div class="col-sm-6"><%= get_index_text('New Ticket Price') %></div>
      <div class="col-sm-6 text-right"><%= link_to 'Back', ticket_prices_path, :class => 'btn btn-primary', :style => 'color:white;background-color:#125687 !important' %></div>
    </div>
    <%= render 'form', ticket_price: @ticket_price %>
  </div>
</div>