config/routes.rb
Rails.application.routes.draw do
  resolve("ActiveStorage::Variant") {|variant, options| main_app.route_for(:rails_variant, variant, options)}


  resources :ticket_prices
  resources :menu_items
  resources :branches
  resources :orders
  resources :cities do
    get :update_data_base, :on => :collection
    get :update_data_base1, :on => :collection
    get :all_cities, :on => :collection
    get :locations_based_on_city, :on => :collection
    get :menu_based_on_location, :on => :collection
    get :tickets_based_on_menu, :on => :collection
  end

  resources :cart_items do
    get :homePage, :on => :collection
    get :division_based_branches, :on => :collection
    get :branch_menu, :on => :collection
    get :display_cart, :on => :collection
    get :change_cart_items, :on => :collection
    get :contactUs, :on => :collection
    get :aboutUs, :on => :collection
    post :place_order, :on => :collection
    post :pay_zippy_response, :on => :collection
    get :orderRecipt, :on => :collection
    get :cityBranchMenu, :on => :collection
    get :test_crm, :on => :collection
  end

  get "cc_avenue/dataFrom"

  get "cc_avenue/ccavRequestHandler"

  post "cc_avenue/ccavResponseHandler"

  root 'cart_items#homePage'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
  has_one_attached :image
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  before_action :set_menu_item, only: [:show, :edit, :update, :destroy]

  # GET /menu_items
  # GET /menu_items.json
  def index
    @menu_items = MenuItem.all
  end

  # GET /menu_items/1
  # GET /menu_items/1.json
  def show
  end

  # GET /menu_items/new
  def new
    @menu_item = MenuItem.new
  end

  # GET /menu_items/1/edit
  def edit
  end

  # POST /menu_items
  # POST /menu_items.json
  def create
    @menu_item = MenuItem.new(menu_item_params)

    respond_to do |format|
      if @menu_item.save
        format.html { redirect_to "/menu_items", notice: 'Menu item was successfully created.' }
        format.json { render :show, status: :created, location: @menu_item }
      else
        format.html { render :new }
        format.json { render json: @menu_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menu_items/1
  # PATCH/PUT /menu_items/1.json
  def update
    respond_to do |format|
      if @menu_item.update(menu_item_params)
        format.html { redirect_to "/menu_items", notice: 'Menu item was successfully updated.' }
        format.json { render :show, status: :ok, location: @menu_item }
      else
        format.html { render :edit }
        format.json { render json: @menu_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menu_items/1
  # DELETE /menu_items/1.json
  def destroy
    @menu_item.destroy
    respond_to do |format|
      format.html { redirect_to menu_items_url, notice: 'Menu item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu_item
      @menu_item = MenuItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def menu_item_params
      params.require(:menu_item).permit(:name, :image, :duration, :has_lay_out, :is_active, :is_private, :total_seats, :branch_id, :city_id,:availability)
    end
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/views/menu_items/_form.html.erb
<%= form_with(model: menu_item, local: true) do |form| %>
  <% if menu_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(menu_item.errors.count, "error") %> prohibited this menu_item from being saved:</h2>

      <ul>
        <% menu_item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-sm-6">
      <div class="form-group">
        <%= form.label :name, :class => 'control-label', :style => "text-transform: capitalize;" %>  <br/>
        <%= form.text_field :name, :class => 'form-control', :placeholder => 'Name', :required => true %>
      </div>

      <div class="form-group">
        <%= form.label :image , :class => 'control-label', :style => "text-transform: capitalize;" %>  <br/>
        <%= form.file_field :image, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :duration , :class => 'control-label', :style => "text-transform: capitalize;" %>  <br/>
        <%= form.text_field :duration, :class => 'form-control', :placeholder => 'Duration', :required => true %>
      </div>

      <div class="form-group">
        <%= form.label :availability , :class => 'control-label', :style => "text-transform: capitalize;" %>  <br/>
        <%= form.text_field :availability , :class => 'form-control', :placeholder => 'Availability', :required => true %>
      </div>

      <div class="form-group">
        <%= form.label :has_lay_out , :class => 'control-label', :style => "text-transform: capitalize;" %>  <br/>
        <%= form.check_box :has_lay_out %>
      </div>

      <div class="form-group">
        <%= form.label :is_active , :class => 'control-label', :style => "text-transform: capitalize;" %>  <br/>
        <%= form.check_box :is_active %>
      </div>

<!--      <div class="form-group">-->
<!--        <%#= form.label :is_private , :class => 'control-label', :style => "text-transform: capitalize;" %>  <br/>-->
        <%#= form.check_box :is_private %>
<!--      </div>-->

      <div class="form-group">
        <%= form.label :total_seats , :class => 'control-label', :style => "text-transform: capitalize;" %>  <br/>
        <%= form.number_field :total_seats , :class => 'form-control', :placeholder => 'Total Seats'%>
      </div>

      <div class="form-group">
        <%= form.label :branch_id , :class => 'control-label', :style => "text-transform: capitalize;" %>  <br/>
        <%= form.select(:branch_id, options_for_select(Branch.all.collect {|u| [u.name, u.id]}, @menu_item.branch_id), {:prompt => 'Select Branch '}, :class => 'form-control') %>
      </div>

      <div class="form-group">
        <%= form.label :city_id , :class => 'control-label', :style => "text-transform: capitalize;" %>  <br/>
        <%= form.select(:city_id, options_for_select(City.all.collect {|u| [u.name, u.id]}, @menu_item.city_id), {:prompt => 'Select City '}, :class => 'form-control') %>
      </div>

      <div class="actions">
        <%= form.submit(:class => 'btn btn-primary', :style => 'background-color:#0575AF') %>
      </div>
    </div>
  </div>
<% end %>

app/views/menu_items/edit.html.erb
<div class="card">
  <div class="card-body">
    <div class="row">
      <div class="col-sm-6"><%= get_index_text('Edit Menu Item') %></div>
      <div class="col-sm-6 text-right"><%= link_to 'Back', menu_items_path, :class => 'btn btn-primary', :style => 'color:white;background-color:#125687 !important' %></div>
    </div>
    <%= render 'form', menu_item: @menu_item %>
  </div>
</div>

app/views/menu_items/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-sm-6"><%= get_index_text('Menu Items') %></div>
  <div class="col-sm-6 text-right"><%= link_to 'New Menu Item', new_menu_item_path, :class => 'btn btn-primary', :style => 'color:white;background-color:#125687 !important' %></div>
</div>
<div class="table-responsive">
  <table id="zero_config" class="table table-striped table-bordered">
    <thead>
    <tr class="tr_style">
      <th>Name</th>
      <th>Image</th>
      <th>Duration</th>
      <th>Availability</th>
      <th>Has lay out</th>
      <th>Is active</th>
      <th>Is private</th>
      <th>Total seats</th>
      <th>Branch</th>
      <th>City</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @menu_items.each do |menu_item| %>
      <tr>
        <td><%= menu_item.name %></td>
        <%# if @user.avatar.attached? %>
          <%#= image_tag(@user.avatar) %>
        <%# end %>
        <td><%= image_tag(menu_item.image.attached? ? menu_item.image : '', :width => '100px')%></td>
        <td><%= menu_item.duration %></td>
        <td><%= menu_item.availability %></td>
        <td><%= menu_item.has_lay_out %></td>
        <td><%= menu_item.is_active %></td>
        <td><%= menu_item.is_private %></td>
        <td><%= menu_item.total_seats %></td>
        <td><%= Branch.find_by_id(menu_item.branch_id).try(:name) %></td>
        <td><%= City.find_by_id(menu_item.city_id ).try(:name)%></td>
        <td><%= link_to 'Edit', edit_menu_item_path(menu_item) %></td>
        <td><%= link_to 'Destroy', menu_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

app/views/menu_items/new.html.erb
<div class="card">
  <div class="card-body">
    <div class="row">
      <div class="col-sm-6"><%= get_index_text('New Menu Item') %></div>
      <div class="col-sm-6 text-right"><%= link_to 'Back', menu_items_path, :class => 'btn btn-primary', :style => 'color:white;background-color:#125687 !important' %></div>
    </div>
    <%= render 'form', menu_item: @menu_item %>
  </div>
</div>