config/routes.rb
Rails.application.routes.draw do
  resolve("ActiveStorage::Variant") {|variant, options| main_app.route_for(:rails_variant, variant, options)}


  resources :ticket_prices
  resources :menu_items
  resources :branches
  resources :orders
  resources :cities do
    get :update_data_base, :on => :collection
    get :update_data_base1, :on => :collection
    get :all_cities, :on => :collection
    get :locations_based_on_city, :on => :collection
    get :menu_based_on_location, :on => :collection
    get :tickets_based_on_menu, :on => :collection
  end

  resources :cart_items do
    get :homePage, :on => :collection
    get :division_based_branches, :on => :collection
    get :branch_menu, :on => :collection
    get :display_cart, :on => :collection
    get :change_cart_items, :on => :collection
    get :contactUs, :on => :collection
    get :aboutUs, :on => :collection
    post :place_order, :on => :collection
    post :pay_zippy_response, :on => :collection
    get :orderRecipt, :on => :collection
    get :cityBranchMenu, :on => :collection
    get :test_crm, :on => :collection
  end

  get "cc_avenue/dataFrom"

  get "cc_avenue/ccavRequestHandler"

  post "cc_avenue/ccavResponseHandler"

  root 'cart_items#homePage'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  require 'httparty'
  require 'uri'
  require 'net/http'
  include ApplicationHelper
  include CartItemsHelper
  include CcAvenueHelper
  skip_before_action :verify_authenticity_token
  before_action :set_cart_item, only: [:show, :edit, :update, :destroy]

  $selectedCity = ''
  $slectedCity_branchList =[]
  $slectedCity_branch = ''
  $vijayavada_branches = ["Bermpark","Bhavani Island Tickets"]
  $menuItems = []
  # GET /cart_items
  # GET /cart_items.json
  def index
    @cart_items = CartItem.all
  end

  # GET /cart_items/1
  # GET /cart_items/1.json
  def show
  end

  # GET /cart_items/new
  def new
    @cart_item = CartItem.new
  end

  # GET /cart_items/1/edit
  def edit
  end

  # POST /cart_items
  # POST /cart_items.json
  def create
    @cart_item = CartItem.new(cart_item_params)

    respond_to do |format|
      if @cart_item.save
        format.html { redirect_to @cart_item, notice: 'Cart item was successfully created.' }
        format.json { render :show, status: :created, location: @cart_item }
      else
        format.html { render :new }
        format.json { render json: @cart_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cart_items/1
  # PATCH/PUT /cart_items/1.json
  def update
    respond_to do |format|
      if @cart_item.update(cart_item_params)
        format.html { redirect_to @cart_item, notice: 'Cart item was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart_item }
      else
        format.html { render :edit }
        format.json { render json: @cart_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cart_items/1
  # DELETE /cart_items/1.json
  def destroy
    @cart_item.destroy
    respond_to do |format|
      format.html { redirect_to cart_items_url, notice: 'Cart item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def homePage
    @cities = City.where("active=?",true)
    $selectedCity = @cities[0].id
    $slectedCity_branchList = Branch.where("city_id=? and is_active=?",$selectedCity,true)
    $slectedCity_branch = $slectedCity_branchList[0].id
    $menuItems = []
    $menuItems = MenuItem.where("branch_id=? and is_active=?",$slectedCity_branch,true)
    render :layout => 'application1'
  end



  def cityBranchMenu
    $slectedCity_branch = params[:branch_name]
    $menuItems = []
    $menuItems = MenuItem.where("branch_id=? and is_active=?",$slectedCity_branch,true)
    render :layout => 'application1'
  end



  def place_order
    @order = Order.new
    @order.first_name = params[:order][:first_name]
    @order.last_name = params[:order][:last_name]
    @order.phone_no = params[:order][:phone_no]
    @order.email = params[:order][:email]
    @order.visit_date = params[:order][:visit_date]
    @order.status = 'Created'
    random_id = UUIDTools::UUID.random_create.to_s.delete '-'
    random_id[0..2] = ''
    @order.merchant_transaction_id = random_id
    @order.is_accepted = true
    @order.save!
    totalPrice = 0.00

    @cartItems = BookedCartItem.where('session_id =?', session[SessionConstants::SESSION_ID])
    @cartItems.each do |item|
    @order_item = OrderItem.new
    @order_item.order_id = @order.id
    @order_item.item_name = item.ticket_name
    @order_item.item_id = 0
    @order_item.item_quandity = item.quandity
    @order_item.price = item.amount
    @order_item.total_price = item.amount * item.quandity
    @order_item.city = item.city
    @order_item.location = item.branch
    @order_item.item_menu_name = item.item
    @order_item.save
    totalPrice = totalPrice +  @order_item.total_price
    end
    @order.transaction_amount = totalPrice
    @order.ticket_no = "APTDC#{Date.today}#{@order.id}"
    @order.barcode = generate_qr("APTDC#{Date.today}#{@order.id}")
    @order.save
    if @order.present?
      @all_order_items = OrderItem.where("order_id=?", @order.id)
    end
    reset_session
    if @order.present?
      payment_url = cc_avenue_details(@order, 'http://bookings.aptdc.in/cart_items/pay_zippy_response')
      redirect_to payment_url
    else
      redirect_to "/"
    end
  end


  def pay_zippy_response
    workingKey="3700EF613748D45F99A6183F16285948"  #Put in the 32 Bit Working Key provided by CCAVENUES.
    encResponse=params[:encResp]
    decResp=decrypt(encResponse,workingKey);
    decResp = decResp.split("&")
    @ccavenueParams = {}
    decResp.each do |key|
      @ccavenueParams[key.from(0).to(key.index("=")-1)] = key.from(key.index("=")+1).to(-1)
    end
    @order = Order.find_by_merchant_transaction_id(@ccavenueParams["order_id"])
    if @order.present?
      @order.status = @ccavenueParams["order_status"]
      @order.transaction_details = @ccavenueParams
      @order.save
    end
    if (@order.present? && @order.status == 'Success') || (@order.present? && @order.status == 'Completed')
      sms = "Dear #{@order.first_name}Your order was booked at APTDC with OrderID #{@order.id},TrnID #{@order.merchant_transaction_id},Fare #{@order.transaction_amount}."
      send_sms(@order.phone_no, sms, 'order booked', @order.id)
      @order_items = OrderItem.where('order_id =?', @order.id)
      UserMailer.orderbooked(@order, @order_items).deliver


      # # CRM  INTIGRATION-------------------------------------------------------------->
      # @auth_token = ''
      # # authToken CALL
      # response =HTTParty.post("https://login5.responsys.net/rest/api/v1.3/auth/token?user_name=aptdc_di&password=Welcome@123$&auth_type=password")
      # @auth_token = response["authToken"]
      # # authToken CALL End
      # url1 = URI("https://api5-023.responsys.net/rest/api/v1.3/lists/CONTACTS_LIST/members")
      # http = Net::HTTP.new(url1.host, url1.port)
      # http.use_ssl = true
      # request1 = Net::HTTP::Post.new(url1)
      # request1["Authorization"] = "#{@auth_token}"
      # request1["Content-Type"] = 'application/json'
      # request1["cache-control"] = 'no-cache'
      # request1["Postman-Token"] = '34265ca8-66a9-4cd9-9b1e-160ba6d18130'
      # request1.body = "{ \r\n\"recordData\" : {\r\n\"fieldNames\" : [ \"MOBILE_NUMBER_\",\"MOBILE_COUNTRY_\", \"EMAIL_ADDRESS_\", \"FIRST_NAME\",\"LAST_NAME\"],\r\n\"records\" : [\r\n[\"+91#{@order.phone_no}\",\"IN\",\"#{@order.email}\", \"#{@order.first_name}\",\"#{@order.last_name}\"]\r\n],\r\n\"mapTemplateName\" : null\r\n},\r\n\"mergeRule\" : {\r\n\"htmlValue\" : \"H\",\r\n\"optinValue\" : \"I\",\r\n\"textValue\" : \"T\",\r\n\"insertOnNoMatch\" : true,\r\n\"updateOnMatch\" : \"REPLACE_ALL\",\r\n\"matchColumnName1\" : \"MOBILE_NUMBER_\",\r\n\"matchColumnName2\" : null,\r\n\"matchOperator\" : \"NONE\",\r\n\"optoutValue\" : \"O\",\r\n\"rejectRecordIfChannelEmpty\" : null,\r\n\"defaultPermissionStatus\" : \"OPTIN\"\r\n}\r\n}"
      # response1 = http.request(request1)
      # url2 = URI("https://ejaa.fa.em2.oraclecloud.com/crmRestApi/resources/11.13.18.05/contacts")
      # http = Net::HTTP.new(url2.host, url2.port)
      # http.use_ssl = true
      # request2 = Net::HTTP::Post.new(url2)
      # request2["Authorization"] = "#{@auth_token}"
      # request2["Content-Type"] = 'application/json'
      # request2["Authorization"] = 'Basic cmFtYW5hQGFwdGRjLmluOkFwdGRjMjAxOCE='
      # request2["cache-control"] = 'no-cache'
      # request2["Postman-Token"] = 'cb75b9dc-9bb6-4289-a856-bb89f295953a'
      # request2.body = "{\r\n    \"FirstName\": \"#{@order.first_name}\",\r\n    \"LastName\": \"#{@order.last_name}\",\r\n    \"EmailAddress\": \"#{@order.email}\",\r\n    \"MobileNumber\":\"+91#{@order.phone_no}\",\r\n    \"Address\": [\r\n        {\r\n            \"Address1\": \"Malaysian Township\",\r\n            \"City\": \"Hyderabad\",\r\n            \"Country\": \"IN\",\r\n            \"State\": \"TS\"\r\n        }\r\n    ]\r\n}"
      # response2 = http.request(request2)
      # url3 = URI("https://api5-023.responsys.net/rest/api/v1.3/lists/CONTACTS_LIST/listExtensions/CRM_HOTEL_CHECKINS/members")
      # http = Net::HTTP.new(url3.host, url3.port)
      # http.use_ssl = true
      # request3 = Net::HTTP::Post.new(url3)
      # request3["Authorization"] = "#{@auth_token}"
      # request3["Content-Type"] = 'application/json'
      # request3["cache-control"] = 'no-cache'
      # request3["Postman-Token"] = '4bb83278-77f8-46d9-8d81-cf5d1c33cca3'
      # request3.body = "{\n\"recordData\" : {\n\"fieldNames\" : [\"MOBILE_NUMBER_\", \"RESERVATION_NO\", \"UNIT_NAME\", \"GUEST_EMAIL_ID\", \"RESERVATION_DATE\", \"EXP_CHECKIN_DATE\", \"EXP_CHECKOUT_DATE\", \"RESERVATION_TYPE\", \"SERVICE_TYPE\"],\n\"records\" : [\n[\"+91#{@order.phone_no}\", \"#{@order.ticket_no}\", \"#{@order_items[0].location} - #{@order_items[0].item_menu_name}\", \"#{@order.email}\", \"#{@order.visit_date}\", \"#{@order.visit_date}\", \"#{@order.visit_date}\", \"ONLINE\", \"BOATING\"]\n],\n\"mapTemplateName\" : null\n},\n\"insertOnNoMatch\" : true,\n\"updateOnMatch\" : \"REPLACE_ALL\",\n\"matchColumnName1\" : \"MOBILE_NUMBER\",\n\"matchColumnName2\" : null\n}"
      # response3 = http.request(request3)
      # url4 = URI("https://api5-023.responsys.net/rest/api/v1.3/folders/%21MasterData/suppData/AP_Hotel_CRM/members")
      # http = Net::HTTP.new(url4.host, url4.port)
      # http.use_ssl = true
      # request4 = Net::HTTP::Post.new(url4)
      # request4["Authorization"] = 'E5yh2U3Gs51gUHJG1l5F4VK7jpNWE1c61P3nXzYkWBLIvyJsUtoDYw'
      # request4["Content-Type"] = 'application/json'
      # request4["cache-control"] = 'no-cache'
      # request4["Postman-Token"] = '9a0f977e-b309-4129-a4f6-a028395c3402'

app/helpers/cart_items_helper.rb
module CartItemsHelper

  class MenuItems
    attr_accessor :name, :taxInclusive, :branch_name,:city,:price,:id
    def initialize(name, taxInclusive, branch_name,city, price,id)
      @name = name
      @taxInclusive = taxInclusive
      @branch_name = branch_name
      @city = city
      @price = price
      @id = id
    end
  end
end

app/views/cart_items/_cityselection.html.erb
<div style="background-image: url(/public2/images/smoothscroll/demo/top-bg.jpg);background-position:center top; background-size:100%;padding: 40px 10px;color:white;min-height: 180px">
  <div class="row" style="margin: 0px">
    <div class="col-sm-2"></div>
    <div class="col-sm-3">
      <div><label class="lable_tag">City</label></div>
      <div>
        <%= select_tag :Division, options_for_select(City.where("active=?",true).collect {|u| [u.name, u.id]}, $selectedCity), :prompt => 'Select Branch',  :onchange => "select_division(this.value)", :class => "form-control slected_tag" %>
      </div>
    </div>
    <div class="col-sm-1"></div>
    <div class="col-sm-3">
      <div><label class="lable_tag">Location</label></div>
      <div> <%= select_tag :branch, options_for_select(Branch.where("city_id=? and is_active=?",$selectedCity,true).collect {|u| [u.name, u.id]}, $slectedCity_branch), :prompt => 'Select Branch',  :onchange => "select_location(this.value)", :class => "form-control slected_tag" %></div>
    </div>
    <div class="col-sm-2"></div>
  </div>
</div>

app/views/cart_items/_form.html.erb
<%= form_with(model: cart_item, local: true) do |form| %>
  <% if cart_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart_item.errors.count, "error") %> prohibited this cart_item from being saved:</h2>

      <ul>
      <% cart_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ticket_id %>
    <%= form.number_field :ticket_id %>
  </div>

  <div class="field">
    <%= form.label :no_of_items %>
    <%= form.number_field :no_of_items %>
  </div>

  <div class="field">
    <%= form.label :is_updated %>
    <%= form.check_box :is_updated %>
  </div>

  <div class="field">
    <%= form.label :session_id %>
    <%= form.text_field :session_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cart_items/_homePageContent.html.erb
<style>
  .city_but {
    display: inline-block;
    float: right;
    vertical-align: top;
  }

  .city_but a {
    -webkit-appearance: none;
    -moz-appearance: none;
    appearance: none;
    position: relative;
    display: inline-block;
    padding: 5px 10px;
    font-weight: bold;
    font-family: inherit;
    border: 1px solid transparent;
    border-radius: 3px;
    background-clip: padding-box;
    font-size: 10px;
    line-height: 18px;
    text-align: center;
    text-decoration: none;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    cursor: pointer;
    background-color: #00a680;
    color: #fff !important;
  }
  .city_but a:hover {
    background-color: #125687;
    color: #fff;
  }
  .city_but a.active {
    background-color: #125687;
    color: #fff;
  }



  .cart_but {
    -webkit-appearance: none;
    -moz-appearance: none;
    appearance: none;
    position: relative;
    display: inline-block;
    padding: 5px 25px;
    font-weight: bold;
    font-family: inherit;
    border: 1px solid transparent;
    border-radius: 3px;
    background-clip: padding-box;
    box-sizing: border-box;
    font-size: 10px;
    line-height: 18px;
    text-align: center;
    text-decoration: none;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    cursor: pointer;
    background-color: #00a680;
    color: #fff !important;
  }

  .cart_but:hover {
    background-color: #125687;
    color: #fff;
  }

  ::-webkit-scrollbar {
    width: 10px;
  }

  /* Track */
  ::-webkit-scrollbar-track {
    background: #f1f1f1;
  }

  /* Handle */
  ::-webkit-scrollbar-thumb {
    background: #888;
  }

  /* Handle on hover */
  ::-webkit-scrollbar-thumb:hover {
    background: #555;
  }

  .selectCityHead {
    background-color: floralwhite;
    color: black;
    padding: 5px;
    text-align: center;
    font-weight: bold;
    font-size: 16px;
   border-top-left-radius: 8px;
    border-top-right-radius: 8px;
    text-transform: uppercase;
  }
</style>

<div class="container">
  <div class="col-sm-12" style="margin: 0px;padding: 14px 0px 0px 0px ">
    <div class="selectCityHead"> <%= Branch.find_by_id($slectedCity_branch).try(:name) %> Boating Activities</div>
  </div>
</div>
<div class="container">
  <div class="row" style="background-color: white;border: 2px solid floralwhite;margin: 0px;background-color: white">
    <div class="col-md-12" style="background-color: white;">
      <div class="row" style="margin: 0px">

        <% $menuItems.each_with_index do |response, index| %>
          <%@ticket_prices = TicketPrice.where("menu_id=?",response.id) %>
          <%if @ticket_prices.present? %>
          <div class="col-sm-6" style="padding: 10px">
            <div style="border: 1px solid #ccc;padding: 5px;min-height: 180px;border-radius:5px; background-image:linear-gradient(#ffffff, #f8f8f8);">
              <div class="row">
                <div class="col-sm-5" style="padding-right:0px;">
                  <div style="padding: 0px">
                    <%= image_tag(response.image.attached? ? response.image : '/public2/images/smoothscroll/demo/pic5.png' ,:style=>"height:170px")%>
                  </div>
                </div>
                <div class="col-sm-7">
                  <div style="font-size: 16px;color: #125687;font-family: Roboto;text-transform: capitalize;font-weight: bold;padding-bottom: 4px"><%= response.name %></div>
                  <div style="font-size: 12px;color: black;padding-bottom: 3px"><span>Avilability : </span> &nbsp;&nbsp; <span style="font-weight: bold"><%= response.availability.present? ? response.availability : "10 Am To 5Pm" %></span></div>
                  <%@ticket_prices = TicketPrice.where("menu_id=?",response.id) %>
                  <div style="max-height:90px;overflow-y: scroll;">
                    <% @ticket_prices.each do |res| %>
                      <div style="font-weight: bold;font-size: 11px;padding: 2px  0px;color: #4a4a4a;text-transform: capitalize !important;">
                        <span style="color: #4a4a4a;"><%= res.name %> </span>
                        <span>&nbsp; - &nbsp;</span>
                        <span style="color: #ff7550;font-weight: bold">Rs. <%= res.price %></span>
                      </div>
                    <% end %>
                  </div>
                  <a href="/cart_items/display_cart?menuId=<%= response.id %>" class="cart_but">BOOK NOW</a>
                </div>
              </div>
            </div>
          </div>
        <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/cart_items/_selected_cart_items.html.erb
<style>

  #mytable1 td {
    border: none !important;
    background-color: white;
    text-align: left;
    color: black;
    padding: 10px;
    font-weight: 600;
    font-family: Roboto;
  }

  #mytable1 th {
    border: none !important;
    text-align: left;
    color: black;
    padding: 10px;
    font-family: "Arial Black";
  }

  #mytable td {
    border: none !important;
    text-align: left;
    background-color: white;
    padding: 15px 5px;
    color: black;
    text-transform: capitalize;
    font-family: Roboto;
  }

  #mytable th {
    border: none !important;
    text-align: left;
    padding: 15px 5px;
    text-transform: capitalize;
    font-family: Roboto;

  }
</style>

<div class="page_content"> Your Order</div>
<div style="padding: 5px;border-bottom: 1px solid #e6e6e6"></div>
<br/>
<div>
  <% @cartItems = BookedCartItem.where('session_id = ?', session[ApplicationHelper::SessionConstants::SESSION_ID]) %>
  <% if @cartItems.present? %>

    <table class="table table-hover" id="mytable" style=" background-color: ghostwhite;padding: 5px">

      <tr>
        <th style="border: none !important;"></th>
        <th>Package Details</th>
        <th> Qty.</th>
        <th> price</th>
      </tr>
      <% @subTotal = 0 %>
      <% @cartItems.each do |item| %>
        <tr style="border-bottom: 1px solid #e6e6e6">
          <td><img src="/public2/images/smoothscroll/demo/pic5.png" height="80px" width="80px"></td>
          <td>
            <div style="font-family: 'Arial Black' !important;padding: 5px 0px;color: #06699B"><%= item.city %></div>
            <div style="font-family: 'Arial Black' !important;padding-bottom: 5px "><%= item.item %></div>
            <div style="color: #0c0c0c;font-weight: 600;"><%= item.ticket_name %>
              - Rs <%= item.amount %> <sub>/ per person</sub></div>
            <div>
              <a onclick="myFunction1(0,'<%= item.id %>')" class="btn-xs btn-danger" style="color: white;background-color: red !important;cursor: pointer">Remove</a>
            </div>
          </td>
          <td style="font-weight: 600"><%= item.quandity %></td>
          <td style="font-weight: 600"> Rs. <%= item.amount * item.quandity %></td>
          <% @subTotal = @subTotal += item.amount * item.quandity %>
        </tr>
      <% end %>
    </table>

    <div class="row" style="margin: 0px">
      <div class="col-sm-6"></div>
      <div class="col-sm-6" style="border: 1px solid black;border-radius: 5px !important;">
        <table class="table table-hover" id="mytable1" style=" background-color: ghostwhite;padding: 10px;">
          <tr>
            <td>Sub Total</td>
            <td> Rs. <%= @subTotal %></td>
          </tr>
          <tr>
            <th>Total Price</th>
            <th style="color: #ff7550"> Rs. <%= (@subTotal).round(2) %></th>
          </tr>
        </table>
      </div>
    </div>

  <% end %>
</div>

app/views/cart_items/branch_menu.html.erb
<style>
  .cart_but {
    -webkit-appearance: none;
    -moz-appearance: none;
    appearance: none;
    position: relative;
    display: inline-block;
    padding: 8px 16px;
    font-weight: bold;
    font-family: inherit;
    border: 1px solid transparent;
    border-radius: 2px;
    background-clip: padding-box;
    box-sizing: border-box;
    font-size: 14px;
    line-height: 18px;
    text-align: center;
    text-decoration: none;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    cursor: pointer;
    background-color: #00a680;
    color: #fff !important;
  }

  .cart_but:hover {
    background-color: #00a680;
    color: #fff;
  }

</style>
<br/><br/><br/><br/><br/><br/><br/>
<main id="tg-main" class="tg-main tg-haslayout">
  <div class="text-center" style="background-color: #06375b;padding: 10px;color: white;font-weight: bold;font-size: 16px">
    Andhra Pradesh Tourism Development Corporation - <%= @branchServiceType %> In <%= @branch %></div>
  <div class="container">
    <br/>
    <% $menuItems.each_with_index do |response, index| %>

      <div class="row" style="padding: 15px 12px;margin: 0px;background-color: <%= index % 2 == 0 ? 'ghostwhite' : '#dddddd21' %>;border-bottom: 2px solid white">

        <div class="col-sm-3">
          <div style="padding: 5px"><img src="/public2/images/smoothscroll/demo/pic5.png"></div>
        </div>
        <div class="col-sm-6">
          <div style="padding: 5px">
            <div style="font-size: 18px;color: #000a12;text-transform: capitalize;font-weight: bold;padding-bottom: 5px"><%= response.name %></div>
            <% response.price.each do |res| %>
              <div style="font-size: 14px;padding: 7px  0px;color: #4a4a4a;text-transform: capitalize !important;">
                <span style="color: #4a4a4a;text-transform: uppercase"><%= res['primaryItemName'] %> </span>
                <span>&nbsp;&nbsp; - &nbsp;&nbsp;</span>
                <span style="color: #ff7550;font-weight: bold">Rs. <%= res['price'] %></span>
              </div>
            <% end %>
            <br/>
          </div>
        </div>
        <div class="col-sm-3">
          <div style="padding: 5px;" class="text-center">
            <br/><br/><br/><br/>
            <a href="/cart_items/display_cart?menuName=<%= response.name %>" class="cart_but">Book Now</a>
          </div>
        </div>
        <div class=" col-sm-12 text-right">
          <span style="background-color:darkorange;color: white;font-size: 10px;font-weight: bold;padding: 4px;border-radius: 3px">
            <%= response.serviceType[0]['brand'] %>
          </span>
        </div>
      </div>
    <% end %>
  </div>
</main>

<script>
    function AddCart(value,) {
        if (value != null || value != '') {
            window.location.href = "/cart_items/display_cart";
        }
    }
</script>

app/views/cart_items/change_cart_items.js.erb
$('#cart_content').html("<%= escape_javascript(render(:partial => "selected_cart_items")) %>");

app/views/cart_items/division_based_branches.js.erb
$('#homePageData_content1').html("<%= escape_javascript(render(:partial => "cityselection")) %>");
$('#homePageData_content').html("<%= escape_javascript(render(:partial => "homePageContent")) %>");

app/views/cart_items/edit.html.erb
<h1>Editing Cart Item</h1>

<%= render 'form', cart_item: @cart_item %>

<%= link_to 'Show', @cart_item %> |
<%= link_to 'Back', cart_items_path %>

app/views/cart_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cart Items</h1>

<table>
  <thead>
    <tr>
      <th>Ticket</th>
      <th>No of items</th>
      <th>Is updated</th>
      <th>Session</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cart_items.each do |cart_item| %>
      <tr>
        <td><%= cart_item.ticket_id %></td>
        <td><%= cart_item.no_of_items %></td>
        <td><%= cart_item.is_updated %></td>
        <td><%= cart_item.session_id %></td>
        <td><%= link_to 'Show', cart_item %></td>
        <td><%= link_to 'Edit', edit_cart_item_path(cart_item) %></td>
        <td><%= link_to 'Destroy', cart_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart Item', new_cart_item_path %>

app/views/cart_items/new.html.erb
<h1>New Cart Item</h1>

<%= render 'form', cart_item: @cart_item %>

<%= link_to 'Back', cart_items_path %>